### ISSUE TITLE
拡張機能でhtmlを挿入

### ISSUE THREAD

**Issue by mfykmn** [mafuyuk/chrome-extension-mock#1]
githubの CodeとIssuesの間にHelloというタブを作成する
そのタブを押すと「hello worldが表示される」

**Comment by Kenta-ihr** [comment]
こんな感じになります。
![2017-04-03 16 55 46](https://cloud.githubusercontent.com/assets/19795560/24600198/72b4828a-188e-11e7-9de9-60489d950f08.png)

**Comment by mfykmn** [comment]
問題なさそうならプルリク出してくれー
